runtime: php55
api_version: 1

runtime_config:
  document_root: web

handlers:
- url: /.*
  script: index.php
- url: /check.*
  script: check.php
  
 env_variables:
  # Replace USER, PASSWORD, DATABASE, and CONNECTION_NAME with the
  # values obtained when configuring your Cloud SQL instance.
  MYSQL_DSN: mysql:unix_socket=/cloudsql/realhackfi:asia-south1:realhackfinal;dbname=ellipsischat
  MYSQL_USER: root
  MYSQL_PASSWORD: 
